name: gigapose
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - setuptools
  - python=3.10
  - pip:
    - torch
    - torchvision
    - omegaconf
    - torchmetrics==0.10.3
    - fvcore
    - iopath
    - xformers==0.0.18
    - opencv-python 
    - pycocotools 
    - matplotlib 
    - scikit-image 
    - onnxruntime 
    - onnx
    - scipy
    - ffmpeg
    - hydra-colorlog
    - hydra-core
    - gdown
    - einops
    - pytorch-lightning==1.8.1
    - pandas
    - ruamel.yaml
    - pyrender
    - wandb
    - distinctipy
    - blenderproc